# Generated by Django 4.0.5 on 2022-07-06 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_question_delete_participant_delete_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('E', 'Easy'), ('M', 'Medium'), ('H', 'Hard'), ('A', 'Alan Turing')], max_length=2),
        ),
    ]
