# Generated by Django 4.0.5 on 2022-07-06 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_alter_question_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='sell_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='solve_count',
            field=models.IntegerField(default=0),
        ),
    ]
